services:
  coffeescoutbackend.api:
    depends_on:
      - database
    restart:
      no
    image: doreml/coffee-scout-backend.api:dev
    env_file:
      - .env
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  database:
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${DATABASESETTINGS__USERID}
      POSTGRES_PASSWORD: ${DATABASESETTINGS__PASSWORD}
      POSTGRES_DB: ${DATABASESETTINGS__DATABASE}
    ports:
      - "5432:5432"