services:
  frontend:
    image: mayaffia/coffee-scout-web
    depends_on:
      - backend
    restart:
      always
    networks:
      - app-network
    ports:
      - "3000:3000"

  backend:
    depends_on:
      database:
        condition: service_healthy
    restart: always
    networks:
      - app-network
      - backend-network
    image: doreml/coffee-scout-backend.api
    env_file:
      - .env
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    logging:
      driver: json-file
      options:
        max-size: "200m"
        max-file: "10"

  database:
    networks:
      - backend-network
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${DATABASESETTINGS__USERID}
      POSTGRES_PASSWORD: ${DATABASESETTINGS__PASSWORD}
      POSTGRES_DB: ${DATABASESETTINGS__DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASESETTINGS__USERID}" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1500M
        reservations:
          cpus: '1.0'
          memory: 1000M
  
  nginx:
    networks:
      - app-network
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

networks:
  app-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  db_data:
    driver: local