services:
  frontend:
    platform: 
      linux/amd64
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING : "true"
      WATCHPACK_POLLING : "true"
    volumes:
      - ../Frontend/web/src:/app/src

    restart:
      always
    networks:
      - app-network
    ports:
      - "3000:3000"
    build:
      context: ../Frontend/web
      dockerfile: ./Dockerfile


  backend:
    depends_on:
      - database
    restart:
      always
    networks:
      - app-network
      - backend-network
    image: doreml/coffee-scout-backend.api:dev
    env_file:
      - .env
    ports:
      - "8000:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Production

  database:
    networks:
      - backend-network
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${DATABASESETTINGS__USERID}
      POSTGRES_PASSWORD: ${DATABASESETTINGS__PASSWORD}
      POSTGRES_DB: ${DATABASESETTINGS__DATABASE}
    ports:
      - "5432:5432"
  
  nginx:
    networks:
      - app-network
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

networks:
  app-network:
    driver: bridge
  backend-network:
    driver: bridge